In [70]:
import pandas as pd
import boto3
import json

In [23]:
# 0. Load the data
s3 = boto3.client('s3')
s3.download_file('noventa-scratch-bucket', 'census_data.json', './tmp/census_data.json')
s3.download_file('noventa-scratch-bucket', 'productivity_cost/2024-06-06/pr.data.0.Current', './tmp/pr.data.0.Current')

In [25]:
# 0. (continued) Load the data into DataFrames
# Load PR Data omtp a dataframe
pr_df = pd.read_csv('./tmp/pr.data.0.Current', sep='\t')

# Load the census JSON file into a dataframe.
with open('./tmp/census_data.json') as f:
    data = json.load(f)

data_to_convert = data['data']
census_df = pd.DataFrame(data_to_convert)

  ID Nation         Nation  ID Year  Year  Population    Slug Nation
0   01000US  United States     2022  2022   331097593  united-states
1   01000US  United States     2021  2021   329725481  united-states
2   01000US  United States     2020  2020   326569308  united-states
3   01000US  United States     2019  2019   324697795  united-states
4   01000US  United States     2018  2018   322903030  united-states
5   01000US  United States     2017  2017   321004407  united-states
6   01000US  United States     2016  2016   318558162  united-states
7   01000US  United States     2015  2015   316515021  united-states
8   01000US  United States     2014  2014   314107084  united-states
9   01000US  United States     2013  2013   311536594  united-states

       series_id          year period         value footnote_codes
0      PRS30006011        1995    Q01         2.600            NaN
1      PRS30006011        1995    Q02         2.100            NaN
2      PRS30006011        1995    Q03         0.900            NaN
3      PRS30006011        1995    Q04         0.100            NaN
4      PRS30006011        1995    Q05         1.400            NaN
...                  ...   ...    ...           ...            ...
35812  PRS88003203        2023    Q02       116.953            NaN
35813  PRS88003203        2023    Q03       116.928            NaN
35814  PRS88003203        2023    Q04       115.824              R
35815  PRS88003203        2023    Q05       116.472              R
35816  PRS88003203        2024    Q01       117.097            NaN

[35817 rows x 5 columns]

In [40]:
# 1. What is the average population between 2013 and 2018?
census_df['Year'] = pd.to_datetime(census_df['Year'], format='%Y')
start_year = pd.to_datetime('2013', format='%Y')
end_year = pd.to_datetime('2018', format='%Y')

filtered_census_df = census_df[(census_df['Year'] >= start_year) & (census_df['Year'] <= end_year)]

population_mean = filtered_census_df['Population'].mean()
population_std = filtered_census_df['Population'].std()

print('Mean:', population_mean)
print('Standard Deviation:', population_std)

Mean: 317437383.0
Standard Deviation: 4257089.5415293295

In [66]:
# 2. For each Series ID, select the year with the highest value (best year)
# Clean the column names
pr_df.columns = pr_df.columns.str.strip()

grouped = pr_df.groupby(['series_id', 'year'])['value'].sum()
grouped = grouped.reset_index()
best_years = grouped.loc[grouped.groupby('series_id')['value'].idxmax()]

print(best_years.to_string())

        series_id       year    value
27    PRS30006011 2022-01-01   20.500
57    PRS30006012 2022-01-01   17.100
63    PRS30006013 1998-01-01  704.125
105   PRS30006021 2010-01-01   17.600
135   PRS30006022 2010-01-01   12.500
169   PRS30006023 2014-01-01  503.171
207   PRS30006031 2022-01-01   20.400
236   PRS30006032 2021-01-01   17.100
243   PRS30006033 1998-01-01  700.712
297   PRS30006061 2022-01-01   38.900
327   PRS30006062 2022-01-01   31.700
358   PRS30006063 2023-01-01  631.806
386   PRS30006081 2021-01-01   23.400
413   PRS30006082 2021-01-01   23.400
440   PRS30006083 2021-01-01  112.459
448   PRS30006091 2002-01-01   43.300
478   PRS30006092 2002-01-01   44.400
517   PRS30006093 2011-01-01  520.088
556   PRS30006101 2020-01-01   33.500
586   PRS30006102 2020-01-01   36.000
619   PRS30006103 2023-01-01  622.072
646   PRS30006111 2020-01-01   31.500
664   PRS30006112 2008-01-01   42.400
709   PRS30006113 2023-01-01  633.119
737   PRS30006131 2021-01-01   17.700
764   PRS30006132 2021-01-01   17.700
791   PRS30006133 2021-01-01  115.286
817   PRS30006151 2020-01-01   26.600
847   PRS30006152 2020-01-01   30.900
877   PRS30006153 2020-01-01  529.610
897   PRS30006161 2010-01-01   50.600
919   PRS30006162 2002-01-01   48.000
960   PRS30006163 2013-01-01  520.484
992   PRS30006171 2015-01-01   11.300
1019  PRS30006172 2015-01-01   11.300
1032  PRS30006173 2001-01-01  121.640
1068  PRS30006211 2010-01-01   35.000
1085  PRS30006212 1997-01-01   38.700
1125  PRS30006213 2007-01-01  529.385
1169  PRS30006221 2021-01-01   12.500
1196  PRS30006222 2021-01-01   12.500
1223  PRS30006223 2021-01-01  115.037
1250  PRS30006231 2021-01-01   18.000
1277  PRS30006232 2021-01-01   18.000
1304  PRS30006233 2021-01-01  112.216
1332  PRS31006011 2022-01-01   20.300
1362  PRS31006012 2022-01-01   20.200
1368  PRS31006013 1998-01-01  704.991
1410  PRS31006021 2010-01-01   19.500
1440  PRS31006022 2010-01-01   14.300
1457  PRS31006023 1997-01-01  503.872
1512  PRS31006031 2022-01-01   23.600
1531  PRS31006032 2011-01-01   21.700
1548  PRS31006033 1998-01-01  702.878
1602  PRS31006061 2022-01-01   36.600
1632  PRS31006062 2022-01-01   32.300
1663  PRS31006063 2023-01-01  632.398
1680  PRS31006081 2010-01-01   16.700
1707  PRS31006082 2010-01-01   16.700
1745  PRS31006083 2021-01-01  107.450
1761  PRS31006091 2010-01-01   42.700
1783  PRS31006092 2002-01-01   49.800
1825  PRS31006093 2014-01-01  510.264
1841  PRS31006101 2000-01-01   34.500
1891  PRS31006102 2020-01-01   40.000
1924  PRS31006103 2023-01-01  619.681
1940  PRS31006111 2009-01-01   37.400
1969  PRS31006112 2008-01-01   58.100
2014  PRS31006113 2023-01-01  643.957
2042  PRS31006131 2021-01-01   11.700
2069  PRS31006132 2021-01-01   11.700
2096  PRS31006133 2021-01-01  113.655
2122  PRS31006151 2020-01-01   27.200
2152  PRS31006152 2020-01-01   35.100
2182  PRS31006153 2020-01-01  529.192
2202  PRS31006161 2010-01-01   64.000
2224  PRS31006162 2002-01-01   54.500
2266  PRS31006163 2014-01-01  513.791
2291  PRS31006171 2009-01-01    8.900
2318  PRS31006172 2009-01-01    8.900
2337  PRS31006173 2001-01-01  111.368
2360  PRS31006211 1997-01-01   47.600
2390  PRS31006212 1997-01-01   55.400
2430  PRS31006213 2007-01-01  527.265
2474  PRS31006221 2021-01-01    8.300
2501  PRS31006222 2021-01-01    8.300
2528  PRS31006223 2021-01-01  114.936
2555  PRS31006231 2021-01-01   12.400
2582  PRS31006232 2021-01-01   12.400
2609  PRS31006233 2021-01-01  108.662
2637  PRS32006011 2022-01-01   21.200
2666  PRS32006012 2021-01-01   14.100
2670  PRS32006013 1995-01-01  726.121
2715  PRS32006021 2010-01-01   14.600
2745  PRS32006022 2010-01-01    9.400
2777  PRS32006023 2012-01-01  503.391
2816  PRS32006031 2021-01-01   18.500
2846  PRS32006032 2021-01-01   18.100
2850  PRS32006033 1995-01-01  710.429
2907  PRS32006061 2022-01-01   43.200
2936  PRS32006062 2021-01-01   30.600
2968  PRS32006063 2023-01-01  630.658
2996  PRS32006081 2021-01-01   26.200
3023  PRS32006082 2021-01-01   26.200
3042  PRS32006083 2013-01-01  116.086
3058  PRS32006091 2002-01-01   35.200
3090  PRS32006092 2004-01-01   31.300
3129  PRS32006093 2013-01-01  517.009
3166  PRS32006101 2020-01-01   34.200
3179  PRS32006102 2003-01-01   34.500
3229  PRS32006103 2023-01-01  625.994
3256  PRS32006111 2020-01-01   34.300
3274  PRS32006112 2008-01-01   34.700
3319  PRS32006113 2023-01-01  629.259
3347  PRS32006131 2021-01-01   20.800
3374  PRS32006132 2021-01-01   20.800
3392  PRS32006133 2012-01-01  117.842
3427  PRS32006151 2020-01-01   27.100
3457  PRS32006152 2020-01-01   26.800
3487  PRS32006153 2020-01-01  531.803
3499  PRS32006161 2002-01-01   36.100
3529  PRS32006162 2002-01-01   31.500
3570  PRS32006163 2013-01-01  520.066
3602  PRS32006171 2015-01-01   15.700
3629  PRS32006172 2015-01-01   15.700
3639  PRS32006173 1998-01-01  135.896
3689  PRS32006211 2021-01-01   22.900
3719  PRS32006212 2021-01-01   24.100
3735  PRS32006213 2007-01-01  520.930
3779  PRS32006221 2021-01-01   16.800
3806  PRS32006222 2021-01-01   16.800
3833  PRS32006223 2021-01-01  115.028
3860  PRS32006231 2021-01-01   22.100
3887  PRS32006232 2021-01-01   22.100
3914  PRS32006233 2021-01-01  114.868
3942  PRS84006011 2022-01-01   22.500
3971  PRS84006012 2021-01-01   26.100
4003  PRS84006013 2023-01-01  534.181
4020  PRS84006021 2010-01-01    6.100
4050  PRS84006022 2010-01-01    7.100
4067  PRS84006023 1997-01-01  518.454
4121  PRS84006031 2021-01-01   27.800
4151  PRS84006032 2021-01-01   27.600
4183  PRS84006033 2023-01-01  525.660
4211  PRS84006041 2021-01-01   37.000
4241  PRS84006042 2021-01-01   33.200
4273  PRS84006043 2023-01-01  580.180
4301  PRS84006051 2021-01-01   64.400
4331  PRS84006052 2021-01-01   68.900
4363  PRS84006053 2023-01-01  704.496
4391  PRS84006061 2021-01-01   53.600
4421  PRS84006062 2021-01-01   53.700
4453  PRS84006063 2023-01-01  693.345
4481  PRS84006081 2021-01-01   79.800
4511  PRS84006082 2021-01-01   91.300
4543  PRS84006083 2023-01-01  718.865
4570  PRS84006091 2020-01-01   25.300
4589  PRS84006092 2009-01-01   30.600
4631  PRS84006093 2021-01-01  554.026
4660  PRS84006101 2020-01-01   39.900
4690  PRS84006102 2020-01-01   46.600
4723  PRS84006103 2023-01-01  659.497
4752  PRS84006111 2022-01-01   29.300
4782  PRS84006112 2022-01-01   24.300
4813  PRS84006113 2023-01-01  597.527
4842  PRS84006131 2022-01-01   52.000
4871  PRS84006132 2021-01-01   54.300
4903  PRS84006133 2023-01-01  619.456
4932  PRS84006141 2022-01-01   39.100
4962  PRS84006142 2022-01-01   35.400
4993  PRS84006143 2023-01-01  607.110
5020  PRS84006151 2020-01-01   32.900
5050  PRS84006152 2020-01-01   40.900
5081  PRS84006153 2021-01-01  549.552
5100  PRS84006161 2010-01-01   21.800
5140  PRS84006162 2020-01-01   25.600
5171  PRS84006163 2021-01-01  552.296
5200  PRS84006171 2020-01-01   12.400
5230  PRS84006172 2020-01-01   18.100
5241  PRS84006173 2001-01-01  559.688
5292  PRS85006011 2022-01-01   23.000
5321  PRS85006012 2021-01-01   26.800
5353  PRS85006013 2023-01-01  535.283
5370  PRS85006021 2010-01-01    6.200
5400  PRS85006022 2010-01-01    7.300
5417  PRS85006023 1997-01-01  519.037
5471  PRS85006031 2021-01-01   28.500
5501  PRS85006032 2021-01-01   29.000
5533  PRS85006033 2023-01-01  527.034
5561  PRS85006041 2021-01-01   36.900
5591  PRS85006042 2021-01-01   33.300
5623  PRS85006043 2023-01-01  581.065
5651  PRS85006051 2021-01-01   62.900
5681  PRS85006052 2021-01-01   68.000
5713  PRS85006053 2023-01-01  704.227
5741  PRS85006061 2021-01-01   53.700
5771  PRS85006062 2021-01-01   53.700
5803  PRS85006063 2023-01-01  694.061
5831  PRS85006081 2021-01-01   75.900
5861  PRS85006082 2021-01-01   89.000
5893  PRS85006083 2023-01-01  717.435
5920  PRS85006091 2020-01-01   25.900
5939  PRS85006092 2009-01-01   30.200
5981  PRS85006093 2021-01-01  553.850
6010  PRS85006101 2020-01-01   40.600
6040  PRS85006102 2020-01-01   47.400
6073  PRS85006103 2023-01-01  658.458
6102  PRS85006111 2022-01-01   28.500
6132  PRS85006112 2022-01-01   23.800
6163  PRS85006113 2023-01-01  597.235
6192  PRS85006131 2022-01-01   50.000
6221  PRS85006132 2021-01-01   51.900
6253  PRS85006133 2023-01-01  617.273
6282  PRS85006141 2022-01-01   37.700
6312  PRS85006142 2022-01-01   33.800
6343  PRS85006143 2023-01-01  605.950
6370  PRS85006151 2020-01-01   33.500
6400  PRS85006152 2020-01-01   41.700
6431  PRS85006153 2021-01-01  549.540
6450  PRS85006161 2010-01-01   22.200
6490  PRS85006162 2020-01-01   25.800
6521  PRS85006163 2021-01-01  552.424
6550  PRS85006171 2020-01-01   12.100
6580  PRS85006172 2020-01-01   18.300
6591  PRS85006173 2001-01-01  558.606
6642  PRS88003011 2022-01-01   25.200
6671  PRS88003012 2021-01-01   25.900
6703  PRS88003013 2023-01-01  537.598
6720  PRS88003021 2010-01-01    6.400
6750  PRS88003022 2010-01-01    7.800
6767  PRS88003023 1997-01-01  517.740
6821  PRS88003031 2021-01-01   26.300
6851  PRS88003032 2021-01-01   27.100
6883  PRS88003033 2023-01-01  529.465
6911  PRS88003041 2021-01-01   46.000
6941  PRS88003042 2021-01-01   35.300
6973  PRS88003043 2023-01-01  589.001
7001  PRS88003051 2021-01-01   72.300
7031  PRS88003052 2021-01-01   67.600
7063  PRS88003053 2023-01-01  714.206
7091  PRS88003061 2021-01-01   50.800
7121  PRS88003062 2021-01-01   52.700
7153  PRS88003063 2023-01-01  702.811
7181  PRS88003081 2021-01-01  106.400
7211  PRS88003082 2021-01-01   91.800
7243  PRS88003083 2023-01-01  730.346
7252  PRS88003091 2002-01-01   20.800
7282  PRS88003092 2002-01-01   24.500
7333  PRS88003093 2023-01-01  556.218
7360  PRS88003101 2020-01-01   39.800
7390  PRS88003102 2020-01-01   45.900
7423  PRS88003103 2023-01-01  663.695
7452  PRS88003111 2022-01-01   26.000
7480  PRS88003112 2020-01-01   21.300
7513  PRS88003113 2023-01-01  596.613
7542  PRS88003121 2022-01-01   59.400
7572  PRS88003122 2022-01-01   47.000
7603  PRS88003123 2023-01-01  553.096
7631  PRS88003131 2021-01-01   54.600
7661  PRS88003132 2021-01-01   52.700
7693  PRS88003133 2023-01-01  619.940
7722  PRS88003141 2022-01-01   37.700
7752  PRS88003142 2022-01-01   33.300
7783  PRS88003143 2023-01-01  606.267
7810  PRS88003151 2020-01-01   32.700
7840  PRS88003152 2020-01-01   40.500
7870  PRS88003153 2020-01-01  549.816
7890  PRS88003161 2010-01-01   27.200
7912  PRS88003162 2002-01-01   25.700
7961  PRS88003163 2021-01-01  553.249
7990  PRS88003171 2020-01-01   15.200
8020  PRS88003172 2020-01-01   14.100
8031  PRS88003173 2001-01-01  558.625
8081  PRS88003181 2021-01-01  186.000
8110  PRS88003182 2020-01-01  323.900
8143  PRS88003183 2023-01-01  903.805
8160  PRS88003191 2010-01-01  153.000
8182  PRS88003192 2002-01-01  282.800
8233  PRS88003193 2023-01-01  767.007
8262  PRS88003201 2022-01-01   36.100
8292  PRS88003202 2022-01-01   28.900
8323  PRS88003203 2023-01-01  582.391

In [69]:
# 3. Report the value of the series with the series_id 'PRS30006032' and period 'Q01' for each year
# Clean the data
pr_df.columns = pr_df.columns.str.strip()
census_df.columns = census_df.columns.str.strip()
pr_df = pr_df.apply(lambda x: x.str.strip() if x.dtype == "object" else x)
census_df = census_df.apply(lambda x: x.str.strip() if x.dtype == "object" else x)

# Convert the 'year' column to datetime to match census_df "Year" column. 
pr_df['year'] = pd.to_datetime(pr_df['year'], format='%Y')

filtered_pr_df = pr_df[(pr_df['series_id'] == 'PRS30006032') & (pr_df['period'] == 'Q01')]
merged_df = pd.merge(filtered_pr_df, census_df, left_on='year', right_on="Year", how='left')
report_df = merged_df[['series_id', 'year', 'period', 'value', 'Population']]

print(report_df.to_string())

      series_id       year period  value   Population
0   PRS30006032 1995-01-01    Q01    0.0          NaN
1   PRS30006032 1996-01-01    Q01   -4.4          NaN
2   PRS30006032 1997-01-01    Q01    2.7          NaN
3   PRS30006032 1998-01-01    Q01    1.0          NaN
4   PRS30006032 1999-01-01    Q01   -4.1          NaN
5   PRS30006032 2000-01-01    Q01    0.5          NaN
6   PRS30006032 2001-01-01    Q01   -6.5          NaN
7   PRS30006032 2002-01-01    Q01   -6.7          NaN
8   PRS30006032 2003-01-01    Q01   -5.6          NaN
9   PRS30006032 2004-01-01    Q01    2.1          NaN
10  PRS30006032 2005-01-01    Q01   -0.6          NaN
11  PRS30006032 2006-01-01    Q01    1.8          NaN
12  PRS30006032 2007-01-01    Q01   -0.7          NaN
13  PRS30006032 2008-01-01    Q01   -3.4          NaN
14  PRS30006032 2009-01-01    Q01  -21.0          NaN
15  PRS30006032 2010-01-01    Q01    3.4          NaN
16  PRS30006032 2011-01-01    Q01    1.7          NaN
17  PRS30006032 2012-01-01    Q01    2.8          NaN
18  PRS30006032 2013-01-01    Q01    0.8  311536594.0
19  PRS30006032 2014-01-01    Q01   -0.1  314107084.0
20  PRS30006032 2015-01-01    Q01   -1.6  316515021.0
21  PRS30006032 2016-01-01    Q01   -1.4  318558162.0
22  PRS30006032 2017-01-01    Q01    0.7  321004407.0
23  PRS30006032 2018-01-01    Q01    0.4  322903030.0
24  PRS30006032 2019-01-01    Q01   -1.6  324697795.0
25  PRS30006032 2020-01-01    Q01   -6.7  326569308.0
26  PRS30006032 2021-01-01    Q01    1.2  329725481.0
27  PRS30006032 2022-01-01    Q01    5.6  331097593.0
28  PRS30006032 2023-01-01    Q01    0.8          NaN
29  PRS30006032 2024-01-01    Q01   -0.2          NaN